schema_version = "1.0.0"
id = "noise_nodes"
version = "0.2.0"
name = "Noise Nodes"
tagline = "Advance Noise Nodes For blender"
maintainer = "haseebahmad295 <quicktiptech@gmail.com>"
type = "add-on"

website = "https://github.com/haseebahmed295/Noise-Nodes"

tags = ["Material" , "Node"]

blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]


[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
]